---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: mixed-line-ending
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11  # or specific tag
      hooks:
          - id: yamlfmt
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
    - repo: https://github.com/timothycrosley/isort
      rev: 5.6.4
      hooks:
          - id: isort
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: v2.6.0
      hooks:
          - id: pylint
            args:
                - --rcfile=./.pylintrc
